"""Add advanced inventory fields

Revision ID: 2fbb86b0ce4f
Revises: 3d706eaac05d
Create Date: 2026-03-31 17:16:54.478803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbb86b0ce4f'
down_revision: Union[str, None] = '3d706eaac05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('catalog_items', sa.Column('is_offer', sa.Boolean(), nullable=False))
    op.add_column('catalog_items', sa.Column('discount_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_items', 'discount_percentage')
    op.drop_column('catalog_items', 'is_offer')
    op.drop_column('catalog_items', 'stock')
    # ### end Alembic commands ###
