"""Add product fields to services

Revision ID: e6abc743f983
Revises: 2fbb86b0ce4f
Create Date: 2026-04-07 23:38:02.459527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6abc743f983'
down_revision: Union[str, None] = '2fbb86b0ce4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('marca', sa.String(), nullable=True))
    op.add_column('services', sa.Column('codigo_modelo', sa.String(), nullable=True))
    op.add_column('services', sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('services', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('services', 'image_url')
    op.drop_column('services', 'specs')
    op.drop_column('services', 'codigo_modelo')
    op.drop_column('services', 'marca')
    # ### end Alembic commands ###
